### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by mkahlkeatnetappdotcom** [libsql/sqlite-antlr4-parser#9]
Hi, I'm Mike Kahlke, a developer at NetApp.
We are using pressly/goose for database migration in our golang microservice.
It in turn pulls in libsql/sqlite-antlr4-parser which has no license. We cannot ship code without a license.
We can't change goose, but we noticed you are directing people to use github.com/tursodatabase/libsql-client-go instead which has an MIT License.
If you could attach a license to libsql/sqlite-antlr4-parser which would it be? Would you consider backporting the MIT license here?

**Comment by haaawk** [comment]
goose depends on libsql/sqlite-antlr4-parser indirectly through tursodatabase/libsql-client-go. tursodatabase/libsql-client-go does not depend on libsql/sqlite-antlr4-parser any more so once goose updates its dependencies the problem will be gone.

**Comment by haaawk** [comment]
But we can add MIT license here as well
